### ISSUE TITLE
Support optional file fileds with forced multipart content type

### ISSUE THREAD

**Issue by squivix** [Eomm/form-auto-content#20]
I am using this library for testing as recommended by `light-my-request` for fastify. I want to have optional field fields in a `multipart/formdata` request. It seems this library determines the content type automatically based on whether there are files in the payload. Is there a way to force a multipart content-type even if the payload has no files? I would set the type as`multipart/formdata` manually but then I can't determine the boundary.

I also tried using `node-formdata` and Node 18's native `FormData` but neither seems compatible with the fake http injection library `light-my-request`.

**Comment by Eomm** [comment]
If the payload has no files, the `application/x-www-form-urlencoded` content type is set.

If you need to force the content-type we need a new [`options` here](https://github.com/Eomm/form-auto-content#options) to control this conditional:

https://github.com/Eomm/form-auto-content/blob/6082e2e1b3387b5af51667cf38dbcb2838ff8911/index.js#L29

then it should work
