### ISSUE TITLE
File from Buffers with filename

### ISSUE THREAD

**Issue by matthiasg** [Eomm/form-auto-content#7]
Form append supports options to allow specifying a filename. This possibility is not passed through. What do you think ?

E.g: 

```
  const form = formAutoContent({
    file: {
      value: Buffer.from('just some content'),
      options: {
        filename: 'test'
      }
    }
  })
```

Where file.value would be used

**Comment by Eomm** [comment]
Yeah, it is for sure useful and doable!
The interface you proposed works as well

Feel free to send a PR if you need it very soon or I will work on it in the next few weeks 👍

**Comment by Eomm** [comment]
Released in 2.1.0 👍

**Comment by matthiasg** [comment]
Sorry to not have sent a PR sooner. Thanks !

**Comment by Eomm** [comment]
Don't worry!

Thank you for the suggestion instead 👍
